### ISSUE TITLE
Add Ctrl + H shortcuts

### ISSUE THREAD

**Issue by jiacai2050** [jiacai2050/better-history#26]
ref: https://addons.mozilla.org/en-US/firefox/addon/history-master/reviews/1073059/

**Comment by jiacai2050** [comment]
https://developer.chrome.com/extensions/commands

**Comment by jiacai2050** [comment]
ping @jueqingsizhe66

**Comment by iamsenthilprabu** [comment]
Waiting for this shortcut implementation.

**Comment by jiacai2050** [comment]
@iamsenthilprabu 
I'm a little confused now, the shortcut to open history is `Ctrl + Shift + H` on firefox, `Ctrl + h`(Windows/Linux, for Mac is ctrl+y) on Chrome.

I test on my macbook, ctrl+y works as expected to open this extension, it seems that we don't need more work on this feature?

**Comment by iamsenthilprabu** [comment]
Sorry for delayed response. I am using firefox on windows. ctrl+h shows the default history in the sidebar, and ctrl+shift+h opens the default history in a new window tab. There should be a shortcut to open the History Master's history page. Correct?

**Comment by xueerzhang** [comment]
I guess my request is similar to [#27](https://github.com/jiacai2050/history-master/issues/27#issue-309557280) which has been closed. It is also related to @iamsenthilprabu's yet coming from the opposite direction so I put it here.

Having used this lovely extension in Chrome on Mac for about a week so far, I find myself wanting to have an option to call Chrome's default history page sometimes. This is mainly because History Master (HM) does not offer to **show all my search results on the same page**, especially when there aren't too many results in total but they are dispersed among many days – say 18 results found in the last 30 days – I'll have to hover/click through all 30 days to view my search results. As a user, while I like that my search results are divided by date which is selectable from the sidebar, I am confused about the *Have a nice day!* message (问号脸) it returns, when I tap/click on the total number of search results at the center of the header bar.

Currently, I can only achieve what I want by manually disable HM from Chrome's extension list. So I guess there are a few choices to solve this somewhat **shortcut-related** issue:
1. Do not override `chrome://history`.
   i. `Add cmd+shift+y to open Chrome's default history page` since HM currently overrides the default cmd+y.
   ii. `The opposite: keep Chrome's default cmd+y to open Chrome's default history page.` Users will use other ways to access HM: tap on the HM's icon from the extension bar next to url box, set cmd+shift+y or whatever keys to open HM (currently I am able to do this from Mac's System Preferences > Keyboards > App Shortcuts), etc.
   iii. `Give user the options in HM's settings` so you don't have to decide between the first two. HM basically does not offer any settings at the moment. The `Extension Options` just opens HM.
2. `Show all search results on one page either by default (immediately after a search is completed) or when users tap/click on the total number of search results` then view by date is still available on the left side.
3. `Put an On/Off switch or temporary disable feature to the dropdown menu` when users right-click HM's icon next to Chrome's url box.

**Comment by jiacai2050** [comment]
Hi @xueerzhang 
Thanks for your detailed suggestion.

Indeed, there are cases to open browser's builtin history for me.
Maybe we can add a switch to enable left-side navigation like what you said.

I will make some update this weekend, if you have any other issues, let me know. Thanks.

**Comment by jiacai2050** [comment]
release 2.1.5, remove override chrome's builtin history https://github.com/jiacai2050/history-master/commit/2f5d1454116ffa65f6b8e98b394512b9c92a7175

Users can configure shortcuts at `chrome://extensions/shortcuts` to activate this extension.

**Comment by xueerzhang** [comment]
> release 2.1.5, remove override chrome's builtin history [2f5d145](https://github.com/jiacai2050/history-master/commit/2f5d1454116ffa65f6b8e98b394512b9c92a7175)
> 
> Users can configure shortcuts at `chrome://extensions/shortcuts` to activate this extension.

Great! totally solved my problem.
